@baseUrl = http://localhost:3000
@session = mysession=MTc0OTMyNjc1M3xEWDhFQVFMX2dBQUJFQUVRQUFBb180QUFBUVp6ZEhKcGJtY01DQUFHYzNSaGRIVnpCbk4wY21sdVp3d0tBQWhoWTNScGRtRjBaUT09fDEwMNRr-eTvIKdIDTSfFrm61NAAZ06WflPGf2t7gHIC

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbjEiLCJpYXQiOjE3NTI3MzY4MzksImV4cCI6MTc1Mjc0MDQzOX0.pDhMKAxo1PkKuPv9AAr-CjaH9Hw4ECTSe6rTTsd3_k4

### Obtener todas las dependencias
GET {{baseUrl}}/dependencies
Cookie: {{session}}
Authorization: Bearer {{token}}

### Obtener una dependencia por ID
GET {{baseUrl}}/dependencies/20
Cookie: {{session}}
Authorization: Bearer {{token}}


### Obtener dependencias por providerId y companyId
GET {{baseUrl}}/dependencies/provider/1/company/8
Cookie: {{session}}
Authorization: Bearer {{token}}


### Obtener nombres de proveedores
GET {{baseUrl}}/dependencies/providers/names/
Content-Type: application/json
Cookie: {{session}}
Authorization: Bearer {{token}}
