@baseUrl = http://localhost:3000
@session = mysession=MTc0OTMyNjc1M3xEWDhFQVFMX2dBQUJFQUVRQUFBb180QUFBUVp6ZEhKcGJtY01DQUFHYzNSaGRIVnpCbk4wY21sdVp3d0tBQWhoWTNScGRtRjBaUT09fDEwMNRr-eTvIKdIDTSfFrm61NAAZ06WflPGf2t7gHIC
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbjEiLCJpYXQiOjE3NTI3MzY4MzksImV4cCI6MTc1Mjc0MDQzOX0.pDhMKAxo1PkKuPv9AAr-CjaH9Hw4ECTSe6rTTsd3_k4

### Obtener todos los ISPs (dropdown CU10.3)
GET {{baseUrl}}/isps
Cookie: {{session}}
Authorization: Bearer {{token}}

### Obtener un ISP por ID
GET {{baseUrl}}/isps/2
Cookie: {{session}}
Authorization: Bearer {{token}}

### Crear un nuevo ISP
POST {{baseUrl}}/isps
Content-Type: application/json
Cookie: {{session}}
Authorization: Bearer {{token}}

{
  "name": "Mi nuevo ISP",
  "ruc": "20999999999"
}
